### PR TITLE
feat: add GitHub Action for building and pushing a container image

### PR DESCRIPTION
**Pull request by linki**
This PR adds a GitHub Action and Dockerfile that creates a multi-arch container image for coingecko-exporter (amd64 and arm64).

The container images will we located at ghcr.io/solarlabsteam/coingecko-exporter.

The master branch will be pushed on each commit. PRs towards master will be built - to check that it works - but not pushed. Any tags of the form `v*` will be built and pushed and tagged. The result will look like this: https://github.com/linki/coingecko-exporter/pkgs/container/coingecko-exporter but under https://github.com/solarlabsteam.

### CODE REVIEW

**Comment by freak12techno** [comment]
LGTM. Can you also remove .DS_Store files? Afaik they don't bring any value here.

**Comment by linki** [comment]
That's what I did 😄 

They are currently pushed to this repo, see https://github.com/solarlabsteam/coingecko-exporter/tree/master/.github

**Comment by freak12techno** [comment]
Whoops, misread what happened here. I'll merge then, thanks for contributing!

**Comment by linki** [comment]
The build works but the created image can't be pulled yet.

```console
$ podman pull ghcr.io/solarlabsteam/coingecko-exporter:master
Trying to pull ghcr.io/solarlabsteam/coingecko-exporter:master...
Error: initializing source docker://ghcr.io/solarlabsteam/coingecko-exporter:master: unable to retrieve auth token: invalid username/password: unauthorized
```

I think you need to make it public like described here: https://docs.github.com/en/packages/learn-github-packages/configuring-a-packages-access-control-and-visibility#configuring-visibility-of-container-images-for-an-organization

**Pull request merged**
